[package]
name = "jio_math"
version = "0.1.0"
edition = "2021"

[lib]
name = "jio_math"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
borsh = "0.9"
borsh-derive = "0.9"

[dev-dependencies]
